### ISSUE TITLE
MPU6050

### ISSUE THREAD

**Issue by vetal1808** [GeeksSect/Astraeus#17]
вероятно при инициализации гироскоп не перенастраевается на 500град/сек и DLPF не включается. необходимо это проверить и устранить.

**Comment by krucios** [comment]
Насчёт DLPF - всё работает. 
Вот подтверждение, основанное на графиках углов.
Mode: 0 (250 HZ)
[DLPF 0 pic](https://www.dropbox.com/s/p8ok3dkbm9z7fpb/DLPF_0.jpg?dl=0)
Mode: 6 (5 HZ)
[DLPF 6 pic](https://www.dropbox.com/s/edf83wc3e2zq2ew/DLPF_6.jpg?dl=0)

**Comment by vetal1808** [comment]
и хорошо и плохо, что на счет гироскопа?

**Comment by vetal1808** [comment]
дело было не в бобине, все работает верно
